# Generated by Django 3.1.3 on 2021-08-18 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Market_list', '0002_auto_20210818_1755'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock_items',
            old_name='vurl',
            new_name='video_url',
        ),
        migrations.RemoveField(
            model_name='stock_items',
            name='video',
        ),
    ]
