# Generated by Django 3.1.3 on 2021-08-25 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Market_list', '0005_stock_items_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='contact',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
